### ISSUE TITLE
Version 1.3.4 Crash in Apple Music

### ISSUE THREAD

**Issue by KentaigaIBE** [ryannair05/libmitsuhaforever#4]
Upgrading to version 1.3.4 caused a problem where (only sometimes) tapping on the music bar to bring up the album art and visualizer would quickly crash the app. No crash log is produced when this happens either, all I know it’s this library and not the tweak itself as version 1.3.3 doesn’t have this issue. Both the actual tweak and AudioSnapshotServer are fully up-to-date. I’m running on iOS 13.5 on an iPhone 11. The only other tweaks that run in the same area are Ablaze by level3tj and Playing, one of ConnorTheDev’s old tweaks. Neither have caused any conflict before as far as I’m aware. Spotify doesn’t have this problem, and neither do any other place where the visualizers show up.

**Comment by rdc74656** [comment]
Yes this happens to me also. iOS 13.3-iPhone 11 pro-u0 5.3.1

**Comment by ryannair05** [comment]
Did version 1.3.5 solve this issue?

**Comment by rdc74656** [comment]
Apologies for not replying sooner, yes it did thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
