### ISSUE TITLE
After starting a song in Apple Music the control center crashes upon launch

### ISSUE THREAD

**Issue by frankie154** [ryannair05/libmitsuhaforever#5]
Every time I start a song in Apple Music and then try to access the control center it crashes and my springboard goes into safe mode. And CrashReporter says the main reason is libmitsuhaforever. And I've been on the latest version 1.3.4 and this bug has been happening all day and I updated it last night. Just letting you know cause it's really bugging me lol literally.

**Comment by frankie154** [comment]
I've also disabled all tweaks one by one that has to do with Apple Music and or the control center to make sure those tweaks weren't the cause. I'm on an iPhone X running iOS 13.5 and I just downgraded to 1.3.3 and my control center crash is no longer.

**Comment by ryannair05** [comment]
Does version 1.3.5 help with this issue?

**Comment by frankie154** [comment]
I got your email reply. Yes it did I forgot to close this issue sorry I'll close it right now. Thank you!
